<div style="display:none;">
	<div class="offline-docs" id="offline">
		<div class="container">

			<?php if (!(isset($this->options['skip-offline']) && $this->options['skip-offline'])): ?>
			<div class="grid grid12 gridlast">
				<div class="green button">
					<a href="../../latest_docs.zip" class="archive"><span>.zip</span></a>
				</div>
			</div>

			<div>
				<div class="grid grid6">
					<div class="blue button">
						<a href="../../latest_docs.tar.gz" class="archive"><span>.tgz</span></a>
					</div>
				</div>
				<div class="grid grid6 gridlast">
					<div class="blue button">
						<a href="../../latest_docs.tar.bz2" class="archive"><span>.bz2</span></a>
					</div>
				</div>
			</div>
			<?php endif; ?>

			<?php if (isset($this->classname)): ?>
			<div>
				<div class="grid grid4">
					<div class="default button">
						<a href="../../xml/<?php echo (string) $this->classname; ?>.xml" class="xml format archive" target="_new" title="XML format"><span>.xml</span></a>
					</div>
				</div>
				<div class="grid grid4">
					<div class="default button">
						<a href="../../json/<?php echo (string) $this->classname; ?>.js" class="json format archive" target="_new" title="JSON format"><span>.json</span></a>
					</div>
				</div>
				<div class="grid grid4 gridlast">
					<div class="default button">
						<a href="../../sphp/<?php echo (string) $this->classname; ?>.sphp" class="sphp format archive" target="_new" title="Serialized PHP format"><span>.sphp</span></a>
					</div>
				</div>
			</div>
			<?php endif; ?>

		</div>
	</div>
</div>
