<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
	"http://www.w3.org/TR/html4/strict.dtd">

<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title><?= strip_tags($template['title']) ?></title>

		<link rel="stylesheet" href="<?= $this->file_depth ?>styles/reset.css" type="text/css" media="screen" charset="utf-8">
		<link rel="stylesheet" href="<?= $this->file_depth ?>styles/main.css" type="text/css" media="screen" charset="utf-8">
		<link rel="stylesheet" href="<?= $this->file_depth ?>styles/syntax.css" type="text/css" media="screen" charset="utf-8">

	    <script src="<?= $this->file_depth ?>scripts/jquery-1.4.2.min.js" type="text/javascript" charset="utf-8"></script>
	    <script src="<?= $this->file_depth ?>scripts/jquery-effect.js" type="text/javascript" charset="utf-8"></script>
	    <script src="<?= $this->file_depth ?>scripts/main.js" type="text/javascript" charset="utf-8"></script>
	    <script src="<?= $this->file_depth ?>scripts/chili/jquery.chili-2.2.js" type="text/javascript" charset="utf-8"></script>
	    <script src="<?= $this->file_depth ?>scripts/chili/recipes.js" type="text/javascript" charset="utf-8"></script>

	</head>
	<body class="body_<?= strtolower($template['doctype']) ?>">

		<div class="banner">
			<span class="type"><?= $template['doctype'] ?></span>
		    <h1><span class="title"><?= isset($template['header']) ? $template['header'] : $template['title'] ?></span>
				<? if (isset($this->xml->class->summary->parentClasses->class->name)): ?>
					<em class="parent">extends <a href="../<?= (string) $this->xml->class->summary->parentClasses->class->name ?>/index.html"><?= (string) $this->xml->class->summary->parentClasses->class->name ?></a></em>
				<? endif; ?></h1>
			<? if (isset($template['subtext'])): ?>
			<p><?= $template['subtext'] ?></p>
			<? endif; ?>
		</div>

		<div id="bodyContent">
			<div id="content">
				<?= $this->body ?>
			</div>
		</div>
	</body>
</html>
