var search_data = {
	"index": {
		"searchIndex": ["assertions", "domassertions", "modelassertions", "responseassertions", "routingassertions", "selectorassertions", "tagassertions"],
		"longSearchIndex": ["actioncontroller", "actioncontroller::assertions", "actioncontroller::assertions", "actioncontroller::assertions", "actioncontroller::assertions", "actioncontroller::assertions", "actioncontroller::assertions"],
		"info": [
			["Assertions", "ActionController", "classes\/ActionController\/Assertions.html", " < ", "", 1],
			["DomAssertions", "ActionController::Assertions", "classes\/ActionController\/Assertions\/DomAssertions.html", " < ", "", 1],
			["ModelAssertions", "ActionController::Assertions", "classes\/ActionController\/Assertions\/ModelAssertions.html", " < ", "", 1],
			["ResponseAssertions", "ActionController::Assertions", "classes\/ActionController\/Assertions\/ResponseAssertions.html", " < ", "A small suite of assertions that test responses from Rails applications. ", 1],
			["RoutingAssertions", "ActionController::Assertions", "classes\/ActionController\/Assertions\/RoutingAssertions.html", " < ", "Suite of assertions to test routes generated by Rails and the handling of requests made to them. ", 1],
			["SelectorAssertions", "ActionController::Assertions", "classes\/ActionController\/Assertions\/SelectorAssertions.html", " < ", "Adds the +assert_select+ method for use in Rails functional test cases, which can be used to make assertions", 1],
			["TagAssertions", "ActionController::Assertions", "classes\/ActionController\/Assertions\/TagAssertions.html", " < ", "Pair of assertions to testing elements in the HTML output of the response. ", 1]
		]
	}
}