#!/usr/bin/env php
<?php

error_reporting(-1);

include_once 'helpers/lexer.class.php';
include_once 'helpers/generator.class.php';


/********************************************************/

$help = array(
	'match:' => '(Required) The file pattern to recursively match (e.g. *.class.php).',
	'output:' => '(Optional) The location to output the raw XML lexer output. Defaults to `output`.',
	'template:' => '(Optional) Edit description.'
);

$options = getopt('', array_keys($help));

if (sizeof($options) === 0)
{
	echo PHP_EOL;
	echo 'NDocs ' . NDocs::VERSION . PHP_EOL;
	echo "    A documentation generator for PHP5 classes and the NaturalDocs documentation format.\n";
	echo PHP_EOL;

	ksort($help);

	foreach ($help as $k => $v)
	{
		echo '--' . preg_replace('/(:*)/', '', $k) . PHP_EOL;
		echo '    ' . $v . PHP_EOL;
	}

	echo "\n\n";

	die();
}
// var_dump($options);
// die();

/********************************************************/

// Get the initial set of defined classes
$before = get_declared_classes();

if (!isset($options['match'])) die('The --match parameter is required.' . PHP_EOL);

// Glob and load
$files = Util::rglob($options['match']);
echo "FILE MATCHES\n";
foreach ($files as $file)
{
	$file = getcwd() . '/' . $file;
	echo '    ' . $file . PHP_EOL;
	include_once $file;
}
echo PHP_EOL;

// Get the updated list of defined classes
$after = get_declared_classes();

// These are the new classes that were introduced
$diff = array_diff($after, $before);

// Do more filtering of the list
$parse_me = array();
echo "CLASS MATCHES\n";
foreach ($diff as $class)
{
	// Exclude classes that contain the word "Exception"
	if (stripos($class, 'Exception') === false)
	{
		$parse_me[] = $class;
		echo '    ' . $class . PHP_EOL;
	}
}
echo PHP_EOL;

/********************************************************/

if (!isset($options['output']) || !$options['output'])
{
	$output = './output';
}
else
{
	$output = $options['output'];
}

echo "RUNNING THE LEXER\n";
foreach ($parse_me as $class)
{
	Lexer::parse_class($class, $output);
}
echo PHP_EOL;

/********************************************************/

$output = realpath($output);
include getcwd() . '/template/template_definition.php';

if (!isset($options['template']) || !$options['template'])
{
	$template = './template';
}
else
{
	$template = $options['template'];
}

echo "RUNNING THE GENERATOR\n";
foreach ($parse_me as $class)
{
	$tmpl = new Template($class, $output, $template);

	foreach ($tmpl->write_to as $w)
	{
		echo '    ' . $w . PHP_EOL;
	}
}
echo PHP_EOL;

/********************************************************/

echo "COPYING STATIC FILES TO OUTPUT DIRECTORY\n";
foreach (CopyFiles::get_files() as $file)
{
	$cmd = 'cp -Rf ' . realpath($template) . DIRECTORY_SEPARATOR . $file . ' ' . realpath($output) . DIRECTORY_SEPARATOR . 'generated' . DIRECTORY_SEPARATOR;
	echo '    ' . $cmd . PHP_EOL;
	shell_exec($cmd);
}
echo PHP_EOL;

/********************************************************/

echo 'DONE.' . PHP_EOL;
echo PHP_EOL;
