<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php if (isset($OPTIONS['product-name']) && isset($OPTIONS['product-version'])): ?>
		<title><?php echo $OPTIONS['product-name'] . ' ' . $OPTIONS['product-version']; ?></title>
		<?php elseif (isset($OPTIONS['product-name'])): ?>
		<title><?php echo $OPTIONS['product-name']; ?></title>
		<?php endif; ?>

		<?php if (!isset($OPTIONS['skip-offline']) || $OPTIONS['skip-offline'] === 'false'): ?>
		<link rel="alternate" type="application/zip" title="Zip Archive" href="latest_docs.zip">
		<link rel="alternate" type="application/x-gzip" title="GZip Archive" href="latest_docs.tar.gz">
		<link rel="alternate" type="application/x-bzip-compressed-tar" title="BZip2 Archive" href="latest_docs.tar.bz2">
		<?php endif; ?>

	    <script src="scripts/production.min.js" type="text/javascript" charset="utf-8"></script>
		<script type="text/javascript" charset="utf-8">
		$(function() {
			$(window).bind('hashchange', function(e) {
				var method = $.bbq.getState('m'),
					property = $.bbq.getState('p'),
					constant = $.bbq.getState('c'),
					classIndex = $.bbq.getState('i'),
					defaultIndex = $.bbq.getState('d');

				if (method) {
					method = method.split('/');
					$('#mainContent').attr('src', 'class/' + method[0].toLowerCase() + '/' + method[1] + '.html');
				}
				else if (property) {
					property = property.split('/');
					$('#mainContent').attr('src', 'class/' + property[0].toLowerCase() + '/properties.html#' + property[1]);
				}
				else if (constant) {
					constant = constant.split('/');
					$('#mainContent').attr('src', 'class/' + constant[0].toLowerCase() + '/constants.html#' + constant[1]);
				}
				else if (classIndex) {
					$('#mainContent').attr('src', 'class/' + classIndex.toLowerCase() + '/index.html');
				}
				else if (defaultIndex) {
					$('#mainContent').attr('src', 'files/included/' + defaultIndex.toLowerCase() + '.html');
				}
				else {
					$('#mainContent').attr('src', 'files/included/readme.html');
				}

				// Write the parent hash to the panel's URL.
				$('#panelContent').get(0).src += location.hash;

			});
			$(window).trigger('hashchange');
		});
		</script>
	</head>
	<frameset cols="300,*" frameborder="1" border="1" bordercolor="#666666" framespacing="1">
		<frame src="panel/index.html" title="Search" name="panel" id="panelContent" />
		<frame src="files/included/readme.html" name="docwin" id="mainContent" />
	</frameset>
</html>
