<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta http-equiv="X-UA-Compatible" content="chrome=1; IE=edge">
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title><?php echo $this->template->titlebar; ?></title>
		<link rel="stylesheet" href="../../styles/production.min.css" type="text/css" media="screen" charset="utf-8">
		<?php echo (isset($this->partials) && isset($this->partials['header'])) ? $this->partials['header'] : ''; ?>

		<?php #if (!isset($OPTIONS['skip-offline']) || $OPTIONS['skip-offline'] === 'false'): ?>
		<!-- <link rel="alternate" type="application/zip" title="Zip Archive" href="latest_docs.zip">
		<link rel="alternate" type="application/x-gzip" title="GZip Archive" href="latest_docs.tar.gz">
		<link rel="alternate" type="application/x-bzip-compressed-tar" title="BZip2 Archive" href="latest_docs.tar.bz2"> -->
		<?php #endif; ?>

	</head>
	<body>
		<div class="ui-layout-center">

			<div class="center-north">
				<form action="http://google.com/search" method="get" target="_blank" id="global-search">
					<select name="query">
						<option value="">Google</option>
					</select>&nbsp;<input type="text" name="q" value="" placeholder="Search...">&nbsp;<input type="submit" value="Search">
				</form>
			</div>

			<div class="center-center center-pane">

				<?php echo (isset($this->partials) && isset($this->partials['prepend'])) ? $this->partials['prepend'] : ''; ?>
				<div class="banner container">
					<div class="left">
						<span class="type"><?php echo $this->template->type; ?></span>
					    <h1><span class="title"><?php echo $this->template->title; ?></span></h1>
						<p><?php echo $this->template->subtext; ?></p>
					</div>
					<?php if (!(isset($this->options['skip-offline']) && $this->options['skip-offline'])): ?>
					<div class="right">
						<p class="downloads"><a href="#offline" class="offline"><img src="../../images/box.png" alt="Download offline documentation" title="Download offline documentation" /></a></p>
					</div>
					<?php endif; ?>
				</div>

				<div id="bodyContent">
					<div id="content">
						<?php echo $this->body ?>
					</div>
				</div>

				<?php include 'partials/offline_docs.phtml'; ?>

				<script src="../../scripts/production.min.js" type="text/javascript" charset="utf-8"></script>
				<script type="text/javascript">
				$(function() {
					var _ = DOMBuilder;

					SyntaxHighlighter.defaults['auto-links'] = false;
					SyntaxHighlighter.all();

					// Toggle source view
					$('a.showsource').click(function(evt) {
						$('div.source').slideToggle('fast');
						evt.preventDefault();
					});

					// Handle offline modal
					$(".banner a.offline").fancybox({
						'transitionIn'	:	'elastic',
						'transitionOut'	:	'elastic',
						'speedIn'		:	200,
						'speedOut'		:	200,
						'overlayShow'	:	true
					});
				});
				</script>

				<?php echo (isset($this->partials) && isset($this->partials['append'])) ? $this->partials['append'] : ''; ?>
			</div>
		</div>

		<div class="ui-layout-west">
			<iframe src="../../panel/index.html" class="west-center"></iframe>
			<div class="west-south">Little helpers.</div>
		</div>
	</body>
</html>
