<div class="method readme">

	<div class="title">
		<strong>AWS SDK for PHP</strong>
	</div>
	<p>Based on <a href="http://getcloudfusion.com">CloudFusion</a>. Includes other third-party software.</p>
	<p>See below for complete copyright and licensing notices.</p>

	<div class="description">
		<h4>AWS SDK for PHP</h4>

		<p><a href="http://aws.amazon.com/php">http://aws.amazon.com/php</a></p>

		<p>Copyright 2010 Amazon.com, Inc. or its affiliates. All Rights Reserved.</p>

		<p>Licensed under the Apache License, Version 2.0 (the &#8220;License&#8221;).
		You may not use this file except in compliance with the License.
		A copy of the License is located at</p>

		<p><a href="http://aws.amazon.com/apache2.0">http://aws.amazon.com/apache2.0</a></p>

		<p>or in the &#8220;license&#8221; file accompanying this file. This file is distributed
		on an &#8220;AS IS&#8221; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
		express or implied. See the License for the specific language governing
		permissions and limitations under the License.</p>

		<h4>CloudFusion</h4>

		<p><a href="http://getcloudfusion.com">http://getcloudfusion.com</a></p>

		<ul>
			<li>Copyright 2005-2010 <a href="http://ryanparman.com">Ryan Parman</a></li>
			<li>Copyright 2007-2010 <a href="http://warpshare.com">Foleeo Inc.</a></li>
			<li>Copyright 2007-2010 &#8220;CONTRIBUTORS&#8221; (see CLOUDFUSION_CONTRIBUTORS.md for a list)</li>
		</ul>

		<p>Redistribution and use in source and binary forms, with or without
		modification, are permitted provided that the following conditions are met:</p>

		<ul>
			<li><p>Redistributions of source code must retain the above copyright notice, this
			list of conditions and the following disclaimer.</p></li>
			<li><p>Redistributions in binary form must reproduce the above copyright notice,
			this list of conditions and the following disclaimer in the documentation
			and/or other materials provided with the distribution.</p></li>
			<li><p>Neither the name of the organization nor the names of its contributors
			may be used to endorse or promote products derived from this software without
			specific prior written permission.</p></li>
		</ul>

		<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS &#8220;AS IS&#8221; AND
		ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
		WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
		IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
		INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
		BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
		OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
		WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
		ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
		POSSIBILITY OF SUCH DAMAGE.</p>

		<p><a href="http://opensource.org/licenses/bsd-license.php">http://opensource.org/licenses/bsd-license.php</a></p>

		<h4>CacheCore</h4>

		<p><a href="http://github.com/skyzyx/cachecore">http://github.com/skyzyx/cachecore</a></p>

		<ul>
			<li>Copyright 2007-2010 <a href="http://ryanparman.com">Ryan Parman</a></li>
			<li>Copyright 2007-2010 <a href="http://warpshare.com">Foleeo Inc.</a></li>
		</ul>

		<p>Redistribution and use in source and binary forms, with or without
		modification, are permitted provided that the following conditions are met:</p>

		<ul>
			<li><p>Redistributions of source code must retain the above copyright notice, this
			list of conditions and the following disclaimer.</p></li>
			<li><p>Redistributions in binary form must reproduce the above copyright notice,
			this list of conditions and the following disclaimer in the documentation
			and/or other materials provided with the distribution.</p></li>
			<li><p>Neither the name of the organization nor the names of its contributors
			may be used to endorse or promote products derived from this software without
			specific prior written permission.</p></li>
		</ul>

		<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS &#8220;AS IS&#8221; AND
		ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
		WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
		IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
		INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
		BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
		OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
		WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
		ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
		POSSIBILITY OF SUCH DAMAGE.</p>

		<p><a href="http://opensource.org/licenses/bsd-license.php">http://opensource.org/licenses/bsd-license.php</a></p>

		<h4>RequestCore</h4>

		<p><a href="http://github.com/skyzyx/requestcore">http://github.com/skyzyx/requestcore</a></p>

		<ul>
			<li>Copyright 2007-2010 <a href="http://ryanparman.com">Ryan Parman</a></li>
			<li>Copyright 2007-2010 <a href="http://warpshare.com">Foleeo Inc.</a></li>
		</ul>

		<p>Redistribution and use in source and binary forms, with or without
		modification, are permitted provided that the following conditions are met:</p>

		<ul>
			<li><p>Redistributions of source code must retain the above copyright notice, this
			list of conditions and the following disclaimer.</p></li>
			<li><p>Redistributions in binary form must reproduce the above copyright notice,
			this list of conditions and the following disclaimer in the documentation
			and/or other materials provided with the distribution.</p></li>
			<li><p>Neither the name of the organization nor the names of its contributors
			may be used to endorse or promote products derived from this software without
			specific prior written permission.</p></li>
		</ul>

		<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS &#8220;AS IS&#8221; AND
		ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
		WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
		IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
		INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
		BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
		OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
		WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
		ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
		POSSIBILITY OF SUCH DAMAGE.</p>

		<p><a href="http://opensource.org/licenses/bsd-license.php">http://opensource.org/licenses/bsd-license.php</a></p>

		<h4>SimplePie Compatibility Test</h4>

		<p><a href="http://simplepie.org">http://simplepie.org</a></p>

		<ul>
			<li>Copyright 2004-2010 <a href="http://ryanparman.com">Ryan Parman</a></li>
			<li>Copyright 2005-2010 <a href="http://gsnedders.com">Geoffrey Sneddon</a></li>
			<li>Copyright 2008-2010 <a href="http://ryanmccue.info">Ryan McCue</a></li>
		</ul>

		<p>Redistribution and use in source and binary forms, with or without
		modification, are permitted provided that the following conditions are met:</p>

		<ul>
			<li><p>Redistributions of source code must retain the above copyright notice, this
			list of conditions and the following disclaimer.</p></li>
			<li><p>Redistributions in binary form must reproduce the above copyright notice,
			this list of conditions and the following disclaimer in the documentation
			and/or other materials provided with the distribution.</p></li>
			<li><p>Neither the name of the organization nor the names of its contributors
			may be used to endorse or promote products derived from this software without
			specific prior written permission.</p></li>
		</ul>

		<p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS &#8220;AS IS&#8221; AND
		ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
		WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
		IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
		INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
		BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
		OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
		WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
		ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
		POSSIBILITY OF SUCH DAMAGE.</p>

		<p><a href="http://opensource.org/licenses/bsd-license.php">http://opensource.org/licenses/bsd-license.php</a></p>
	</div>
</div>
