<? foreach ($this->xml->class->properties->property as $property): ?>
<div class="method">
	<div class="title" id="<?= $property->name ?>">
		<a name="<?= $property->name ?>" id="<?= $property->name ?>"></a><strong><?= $property->name ?></strong>
	</div>

	<div class="description">
		<? if (isset($property->description)): ?>
			<? foreach ($property->description->line as $line): ?>
				<p><?= Util::entitize($line) ?></p>
			<? endforeach; ?>
		<? endif; ?>

		<? if (isset($property->inherited)): ?>
			<p class="parent"><em>Inherited from <a href="../<?= $property->inherited->attributes()->from ?>/index.html"><?= $property->inherited->attributes()->from ?></a></em></p>
		<? endif; ?>

	</div>
</div>
<? endforeach; ?>
