<div class="method readme">

	<div class="title">
		<strong>Build awesome, cloud-based web applications in a fraction of the time!</strong>
	</div>
	<ul>
		<li>Fast, powerful PHP toolkit with an easy to learn, consistent API.</li>
		<li>Highly extensible framework for easily adding new services, helpers or extensions.</li>
		<li>Ridiculously thorough API reference, code samples and tutorials.</li>
		<li>Only has a few requirements, and should even run on most shared hosting plans.</li>
	</ul>

	<br>

	<div class="title">
		<strong>Using the SDK Reference</strong>
	</div>
	<ul>
		<li>Press <code>up</code>, <code>down</code>, <code>left</code> and <code>right</code> to navigate the browse panel. Press <code>enter</code> to make a selection. Press <code>esc</code> to clear searches.</li>
		<li>Searching will intelligently find results that start with (first), contain (second) and smart match (third) the words you're looking for.</li>
		<li>Looking for a method that exists in multiple classes? Narrow your results by following your search term with the class you want to search.</li>
		<li>Tested with Safari 4, Firefox 3, Opera 9.5, Chrome, IE8. IE 6 &amp; 7 are usable but <em>painfully</em> slow.</li>
	</ul>

	<br>

	<div class="title">
		<strong>SDK Requirements</strong>
	</div>
	<div class="description">
		<h4>Base Requirements</h4>
		<p>If you're not sure if your PHP installation supports these, you can check by either running <a href="http://php.net/phpinfo">phpinfo()</a> in a browser, or running <code>php -i</code> from the command line.</p>
		<ul>
			<li><a href="http://www.php.net/ChangeLog-5.php#5.1.4">PHP 5.1.4</a> or newer; <a href="http://www.php.net/ChangeLog-5.php#5.2.0">PHP 5.2</a> or later is faster.</li>
			<li><a href="http://php.net/curl">cURL</a> 7.15 with OpenSSL (i.e. supports <code>https</code>)</li>
			<li><a href="http://php.net/simplexml">SimpleXML</a></li>
			<li><a href="http://php.net/spl">Standard PHP Library (SPL)</a></li>
		</ul>

		<h4>Caching Requirements</h4>
		<p>Want to be able to leverage response caching? You'll also need one of these sets, depending on the kind of caching you want to use:</p>
		<ul>
			<li><a href="http://php.net/apc">APC</a> extension</li>
			<li><a href="http://xcache.lighttpd.net">XCache</a> extension</li>
			<li><a href="http://php.net/memcache">Memcache</a> extension, with <a href="http://memcached.org">memcached</a></li>
			<li><a href="http://php.net/sqlite3">SQLite 3</a>, <a href="http://php.net/PDO">PDO</a> and the <a href="http://php.net/pdo_sqlite">PDO_SQLITE</a> driver</li>
		</ul>
	</div>

	<br>

	<div class="title">
		<strong>On the shoulders of giants&hellip;</strong>
	</div>
	<p>The CloudFusion SDK and its documentation wouldn't have been made possible without the following projects:</p>
	<div class="description">
		<h4>Inspiration</h4>
		<ul>
			<li><a href="http://railsapi.com">Rails Searchable API Doc</a> &mdash; Smart search, beautifully packed, for Ruby on Rails.</li>
			<li><a href="http://james.padolsey.com/jquery/">jQuery source viewer</a> &mdash; Lookup the implementation for any jQuery method.</li>
		</ul>

		<h4>Open source projects</h4>
		<ul>
			<li><a href="http://github.com/skyzyx/requestcore">RequestCore</a> &mdash; Handles all of the HTTP requests and responses, including batch requests. (BSD-licensed)</li>
			<li><a href="http://github.com/skyzyx/cachecore">CacheCore</a> &mdash; Handles the response caching with support for multiple storage types. (BSD-licensed)</li>
			<li><a href="http://github.com/skyzyx/vanity">Vanity</a> &mdash; Uses PHP's Reflection API to generate source reference documentation. (MIT-licensed)</li>
			<li><a href="http://github.com/voloko/sdoc/">SDoc</a> &mdash; The UI template with browse/search support. (MIT-licensed)</li>
			<li><a href="http://michelf.com/projects/php-markdown/">PHP Markdown</a> &mdash; Useful for converting large, free-form blocks of text into HTML. (BSD-licensed)</li>
		</ul>
	</div>

</div>
