<div class="method readme">

	<div class="title">
		<strong>Using the documentation</strong>
	</div>
	<ul>
		<li>Press <code>up</code>, <code>down</code>, <code>left</code> and <code>right</code> to navigate the browse panel. Press <code>enter</code> to make a selection. Press <code>esc</code> to clear searches.</li>
		<li>Searching will intelligently find results that start with (first), contain (second) and smart match (third) the words you're looking for.</li>
		<li>Looking for a method that exists in multiple classes? Narrow your results by following your search term with the class you want to search.</li>
		<li>Automatically trigger a search by appending a <code>?q=search+term</code> query string.</li>
		<li>Tested with Safari 4, Firefox 3, Opera 9.5, Chrome, IE8. IE 6 &amp; 7 are usable but <em>painfully</em> slow.</li>
	</ul>

	<br>

	<div class="title">
		<strong>On the shoulders of giants&hellip;</strong>
	</div>
	<p>This documentation wouldn't have been made possible without the following projects:</p>
	<div class="description">
		<ul>
			<li><a href="http://github.com/skyzyx/vanity/">Vanity</a> &mdash; Uses PHP's Reflection API to generate source reference documentation. (MIT-licensed)</li>
			<li><a href="http://github.com/voloko/sdoc/">SDoc</a> &mdash; The UI template with browse/search support. (MIT-licensed)</li>
			<li><a href="http://code.google.com/p/spyc/">Spyc</a> &mdash; Pure PHP YAML parser. (MIT-licensed)</li>
			<li><a href="http://code.google.com/p/jquery-chili-js/">Chili</a> &mdash; Syntax highlighter for source code. (MIT-licensed)</li>
			<li><a href="http://jquery.com">jQuery</a> &mdash; A fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development. (MIT-licensed)</li>
			<li><a href="http://benalman.com/projects/jquery-bbq-plugin/">jQuery BBQ</a> &mdash; Leverages the HTML5 hashchange event to allow simple, yet powerful bookmarkable #hash history. (MIT-licensed)</li>
			<li><a href="http://github.com/skyzyx/examplify/">Examplify!</a> &mdash; Provides a comment-based syntax for editing working code samples. (MIT-licensed)</li>
			<li><a href="http://github.com/skyzyx/phpt/">PHPT Parser</a> &mdash; Parses PHPT unit test files. (MIT-licensed)</li>
			<li><a href="http://michelf.com/projects/php-markdown/">PHP Markdown</a> &mdash; Useful for converting large, free-form blocks of text into HTML. (BSD-licensed)</li>
		</ul>
	</div>

</div>
