<?php if (isset($this->data->class->constants->constant)): ?>
	<?php foreach ($this->data->class->constants->constant as $constant): ?>
	<div class="method">
		<div class="title" id="<?php echo (string) $constant->name ?>">
			<a name="<?php echo (string) $constant->name ?>" id="<?php echo (string) $constant->name ?>"></a><strong><?php echo (string) $constant->name ?></strong>
		</div>

		<div class="description">
			<p><em><?php echo (string) $constant->value->attributes()->type ?></em> <code><?php echo (string) $constant->value ?></code></p>
		</div>
	</div>
	<?php endforeach; ?>
<?php else: ?>
	<div class="method">
		<p>There are no constants defined in this class.</p>
	</div>
<?php endif; ?>
