<?php if (isset($this->data->class->properties->property)): ?>
	<?php foreach ($this->data->class->properties->property as $property): ?>
	<div class="method">
		<div class="title" id="<?php echo $property->name ?>">
			<a name="<?php echo $property->name ?>" id="<?php echo $property->name ?>"></a><strong><?php echo $property->name ?></strong>
		</div>

		<div class="description">
			<?php if (isset($property->description)): ?>
				<?php echo (string) $property->description; ?>
			<?php endif; ?>
			<?php if (isset($property->inheritance)): ?>
				<p class="footnote">Inherited from <a href="../<?php echo (string) $property->inheritance->class->name; ?>/index.html"><?php echo (string) $property->inheritance->class->name; ?></a></p>
			<?php endif; ?>

		</div>
	</div>
	<?php endforeach; ?>
<?php else: ?>
	<div class="method">
		<p>There are no properties defined in this class.</p>
	</div>
<?php endif; ?>
